site_name: linux knowledge
repo_url: https://github.com/Seme4eg/linux
repo_name: linux knowledge
nav:
    - Installation and setup: index.md
    - Terminal: terminal_commands.md
    - Root directories: linux_dirs.md
theme:
    name: material
    palette:
        scheme: slate
        primary: cyan
        accent: cyan
    font:
        text: Montserrat
    features:
        - instant
    icon:
        repo: fontawesome/brands/gitkraken

markdown_extensions:
    - toc:
        permalink: true
